# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Latchfield Technologies http://latchfield.com
name: "Prepare the Python environment"
description: "Prepares the Python environment leveraging cache where possible"

inputs:
  skip_cache_restore:
    description: "Skip restoring the uv cache even if it exists"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Configure system
      id: config
      shell: bash
      run: |
        # Ensure local binaries are on the PATH
        echo "${HOME}/.local/bin" >> "$GITHUB_PATH"
        echo "${HOME}/.local/share/pipx/bin/" >> "$GITHUB_PATH"
        echo "${GITHUB_WORKSPACE}/.venv/bin" >> "$GITHUB_PATH"

        # Configure pipx environment
        echo "PIPX_HOME=${HOME}/.local/share/pipx" >> $GITHUB_ENV
        echo "PIPX_BIN_DIR=${HOME}/.local/share/pipx/bin" >> $GITHUB_ENV

        # Configure uv environment
        echo "UV_LINK_MODE=symlink" >> $GITHUB_ENV

        # Create report directories        
        set -x
        mkdir -p ./reports/tests
        mkdir -p ./reports/security
        mkdir -p ./reports/analysis
        set +x

        # Resolve the uv version to install
        SPEC="$(grep -Po 'required-version\s*=\s*"\K[^"]*' pyproject.toml)"
        PACKAGE="uv"
        UV_VERSION=$(python3 -c "import sys, json, packaging.specifiers, packaging.version; spec = packaging.specifiers.SpecifierSet('${SPEC}'); data = json.load(sys.stdin); print(max((v for v in data['releases'].keys() if v in spec), key=packaging.version.Version, default=''))" < <(curl -s "https://pypi.org/pypi/${PACKAGE}/json"))
        echo "uv_version=${UV_VERSION}" >> $GITHUB_OUTPUT

    # Cache Lookups
    - name: Lookup pipx cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 #v5.0.3
      id: pipx_lookup
      with:
        lookup-only: true
        path: |
          /home/runner/.local/share/pipx/
        key: pipx-uv-${{ steps.config.outputs.uv_version }}

    - name: Lookup uv cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 #v5.0.3
      id: uv_lookup
      with:
        lookup-only: true
        path: |
          /home/runner/.cache/uv/
          /home/runner/.local/share/uv/
          .venv
        key: uv-${{ hashFiles('uv.lock') }}

    # Pipx Cache Control
    - name: Restore pipx cache
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 #v5.0.3
      if: ${{ steps.pipx_lookup.outputs.cache-hit == 'true' && (inputs.skip_cache_restore != 'true' || steps.uv_lookup.outputs.cache-hit != 'true') }}
      with:
        path: |
          /home/runner/.local/share/pipx/
        key: pipx-uv-${{ steps.config.outputs.uv_version }}

    - name: Report pipx cache restore skipped
      if: ${{ steps.pipx_lookup.outputs.cache-hit == 'true' && inputs.skip_cache_restore == 'true' && steps.uv_lookup.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        echo "::notice::Skipped pipx cache restoration due to skip_cache_restore==true"

    # UV Cache Control
    - name: Restore uv cache
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 #v5.0.3
      if: ${{ steps.uv_lookup.outputs.cache-hit == 'true' && inputs.skip_cache_restore != 'true' }}
      with:
        path: |
          /home/runner/.cache/uv/
          /home/runner/.local/share/uv/
          .venv
        key: uv-${{ hashFiles('uv.lock') }}

    - name: Report uv cache restore skipped
      if: ${{ steps.uv_lookup.outputs.cache-hit == 'true' && inputs.skip_cache_restore == 'true' }}
      shell: bash
      run: |
        echo "::notice::Skipped uv cache restoration due to skip_cache_restore==true"

    # Install tools and dependencies
    - name: Install pipx tools
      if: ${{ steps.pipx_lookup.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        set -x
        pipx environment
        pipx install -f "uv==${{ steps.config.outputs.uv_version }}"

    - name: Warm UV cache
      if: ${{ steps.uv_lookup.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        set -x
        uv run just warm_uv_cache

    - name: Install package dependencies
      if: ${{ steps.uv_lookup.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        set -x
        uv sync --all-extras

    - name: Report on environment
      if: ${{ steps.uv_lookup.outputs.cache-hit != 'true' || inputs.skip_cache_restore != 'true' }}
      shell: bash
      run: |
        set -x
        which uv
        readlink -f $(which uv)
        uv --version
        uv cache dir
        which python
        python --version